### ISSUE TITLE
NullPointerException when using api /oauth2/userinfo

### ISSUE THREAD

**Issue by love98ooo** [NJUPT-SAST/sast-link-java-sdk#3]
The SDK tries to use `resultMap.get("userId")`  and throws a `NullPointerException`.

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "resultMap" is null
```

The actual response may includes null value: 

``` json
{
    "Success": true,
    "ErrCode": 200,
    "ErrMsg": "",
    "Data": {
        "avatar": null,
        "badge": null,
        "bio": null,
        "dep": "",
        "email": "b22050029@njupt.edu.cn",
        "hide": null,
        "link": null,
        "nickname": "b22050029",
        "org": "",
        "userId": "b22050029"
    }
}
```

You should not only check the null of the body, but also the contents in the body.

**Comment by feellmoose** [comment]
# check every value provided by sast-link before accepting them

The issue has frequently emerged in relation to sast-link, and the crux of the matter is that sast-link lacks reliable and comprehensive documentation to inform third-party developers or other stakeholders about any changes made to its API in each version. Moreover, it fails to clearly indicate what modifications have been made to the API and how certain values may have been newly defined.

Therefore, I would advise all third-party users to await the full deployment of sast-link before commencing the utilization of its login functionalities.

What sast-link-sdk could do right now is, check every value provided by sast-link before accepting them.

I will fix it as soon as passible. Thanks for your issue and good luck nya~.
